//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicClient.ServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProxy.IServiceProxy")]
    public interface IServiceProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetContacts", ReplyAction="http://tempuri.org/IServiceProxy/GetContactsResponse")]
        string GetContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetContacts", ReplyAction="http://tempuri.org/IServiceProxy/GetContactsResponse")]
        System.Threading.Tasks.Task<string> GetContactsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProxyChannel : BasicClient.ServiceProxy.IServiceProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProxyClient : System.ServiceModel.ClientBase<BasicClient.ServiceProxy.IServiceProxy>, BasicClient.ServiceProxy.IServiceProxy {
        
        public ServiceProxyClient() {
        }
        
        public ServiceProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetContacts() {
            return base.Channel.GetContacts();
        }
        
        public System.Threading.Tasks.Task<string> GetContactsAsync() {
            return base.Channel.GetContactsAsync();
        }
    }
}
